<Project Sdk="Microsoft.NET.Sdk">

    <ItemGroup>
        <ProjectReference Include="..\LendingSystem.Lending.Domain\LendingSystem.Lending.Domain.csproj" />
        <ProjectReference Include="..\LendingSystem.SharedKernel.Application\LendingSystem.SharedKernel.Application.csproj" />
        <ProjectReference Include="..\LendingSystem.SharedKernel.Domain\LendingSystem.SharedKernel.Domain.csproj" />
        <ProjectReference Include="..\LendingSystem.SharedKernel.WebApi\LendingSystem.SharedKernel.WebApi.csproj" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="FluentValidation" Version="12.1.1" />
      <PackageReference Include="MediatR" Version="14.1.0" />
    </ItemGroup>

    <ItemGroup>
      <Folder Include="Abstractions\Items\" />
      <Folder Include="Commons\Items\" />
    </ItemGroup>

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

</Project>
