// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.20.3
// source: proto/video.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DownloadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadRequest) Reset() {
	*x = DownloadRequest{}
	mi := &file_proto_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadRequest) ProtoMessage() {}

func (x *DownloadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadRequest.ProtoReflect.Descriptor instead.
func (*DownloadRequest) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{0}
}

func (x *DownloadRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type DownloadResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*DownloadResponse_Progress
	//	*DownloadResponse_FileChunk
	//	*DownloadResponse_ErrorMes
	Payload       isDownloadResponse_Payload `protobuf_oneof:"payload"`
	Filename      string                     `protobuf:"bytes,4,opt,name=filename,proto3" json:"filename,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DownloadResponse) Reset() {
	*x = DownloadResponse{}
	mi := &file_proto_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DownloadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DownloadResponse) ProtoMessage() {}

func (x *DownloadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DownloadResponse.ProtoReflect.Descriptor instead.
func (*DownloadResponse) Descriptor() ([]byte, []int) {
	return file_proto_video_proto_rawDescGZIP(), []int{1}
}

func (x *DownloadResponse) GetPayload() isDownloadResponse_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DownloadResponse) GetProgress() int32 {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_Progress); ok {
			return x.Progress
		}
	}
	return 0
}

func (x *DownloadResponse) GetFileChunk() []byte {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_FileChunk); ok {
			return x.FileChunk
		}
	}
	return nil
}

func (x *DownloadResponse) GetErrorMes() string {
	if x != nil {
		if x, ok := x.Payload.(*DownloadResponse_ErrorMes); ok {
			return x.ErrorMes
		}
	}
	return ""
}

func (x *DownloadResponse) GetFilename() string {
	if x != nil {
		return x.Filename
	}
	return ""
}

type isDownloadResponse_Payload interface {
	isDownloadResponse_Payload()
}

type DownloadResponse_Progress struct {
	Progress int32 `protobuf:"varint,1,opt,name=progress,proto3,oneof"`
}

type DownloadResponse_FileChunk struct {
	FileChunk []byte `protobuf:"bytes,2,opt,name=file_chunk,json=fileChunk,proto3,oneof"`
}

type DownloadResponse_ErrorMes struct {
	ErrorMes string `protobuf:"bytes,3,opt,name=error_mes,json=errorMes,proto3,oneof"`
}

func (*DownloadResponse_Progress) isDownloadResponse_Payload() {}

func (*DownloadResponse_FileChunk) isDownloadResponse_Payload() {}

func (*DownloadResponse_ErrorMes) isDownloadResponse_Payload() {}

var File_proto_video_proto protoreflect.FileDescriptor

const file_proto_video_proto_rawDesc = "" +
	"\n" +
	"\x11proto/video.proto\x12\x05video\"#\n" +
	"\x0fDownloadRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x97\x01\n" +
	"\x10DownloadResponse\x12\x1c\n" +
	"\bprogress\x18\x01 \x01(\x05H\x00R\bprogress\x12\x1f\n" +
	"\n" +
	"file_chunk\x18\x02 \x01(\fH\x00R\tfileChunk\x12\x1d\n" +
	"\terror_mes\x18\x03 \x01(\tH\x00R\berrorMes\x12\x1a\n" +
	"\bfilename\x18\x04 \x01(\tR\bfilenameB\t\n" +
	"\apayload2V\n" +
	"\fVideoService\x12F\n" +
	"\x11DownloadAndStream\x12\x16.video.DownloadRequest\x1a\x17.video.DownloadResponse0\x01B+Z)github.com/onon1101/lending-backend/protob\x06proto3"

var (
	file_proto_video_proto_rawDescOnce sync.Once
	file_proto_video_proto_rawDescData []byte
)

func file_proto_video_proto_rawDescGZIP() []byte {
	file_proto_video_proto_rawDescOnce.Do(func() {
		file_proto_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)))
	})
	return file_proto_video_proto_rawDescData
}

var file_proto_video_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_video_proto_goTypes = []any{
	(*DownloadRequest)(nil),  // 0: video.DownloadRequest
	(*DownloadResponse)(nil), // 1: video.DownloadResponse
}
var file_proto_video_proto_depIdxs = []int32{
	0, // 0: video.VideoService.DownloadAndStream:input_type -> video.DownloadRequest
	1, // 1: video.VideoService.DownloadAndStream:output_type -> video.DownloadResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_video_proto_init() }
func file_proto_video_proto_init() {
	if File_proto_video_proto != nil {
		return
	}
	file_proto_video_proto_msgTypes[1].OneofWrappers = []any{
		(*DownloadResponse_Progress)(nil),
		(*DownloadResponse_FileChunk)(nil),
		(*DownloadResponse_ErrorMes)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_video_proto_rawDesc), len(file_proto_video_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_video_proto_goTypes,
		DependencyIndexes: file_proto_video_proto_depIdxs,
		MessageInfos:      file_proto_video_proto_msgTypes,
	}.Build()
	File_proto_video_proto = out.File
	file_proto_video_proto_goTypes = nil
	file_proto_video_proto_depIdxs = nil
}
