// <auto-generated />
using System;
using LendingSystem.SharedKernel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LendingSystem.SharedKernel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    [Migration("20260512222600_MakeItemOwnerAndDescriptionRequired")]
    partial class MakeItemOwnerAndDescriptionRequired
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseSerialColumns(modelBuilder);

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ItemId"));

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("current_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("maker");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("object_name");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer")
                        .HasColumnName("owner_id");

                    b.HasKey("ItemId")
                        .HasName("items_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.MediaEntity", b =>
                {
                    b.Property<int>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("media_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("MediaId"));

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("object_id");

                    b.Property<int?>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("MediaId")
                        .HasName("media_pkey");

                    b.HasIndex("ObjectId");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_media_order_id");

                    b.ToTable("media", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderDetailEntity", b =>
                {
                    b.Property<int>("ObjectDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_detail_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("ObjectDetailId"));

                    b.Property<DateTimeOffset?>("ActualReturnTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("actual_return_time");

                    b.Property<string>("DetailStatus")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("detail_status");

                    b.Property<int>("ObjectId")
                        .HasColumnType("integer")
                        .HasColumnName("item_id");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    b.HasKey("ObjectDetailId")
                        .HasName("order_details_pkey");

                    b.HasIndex("ObjectId");

                    b.HasIndex("OrderId");

                    b.ToTable("order_details", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("order_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("OrderId"));

                    b.Property<int?>("BorrowerId")
                        .HasColumnType("integer")
                        .HasColumnName("borrower_id");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("borrower_name");

                    b.Property<DateTimeOffset>("EndTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("end_time");

                    b.Property<DateTimeOffset>("StartTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("BorrowerId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseSerialColumn(b.Property<int>("UserId"));

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("users_name_key");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_name_english_letters", "name ~ '^[A-Za-z]+$'");
                        });
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.MediaEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", "Item")
                        .WithMany("Media")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired()
                        .HasConstraintName("fk_media_item");

                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", "Order")
                        .WithMany("Media")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_media_order");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderDetailEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", "Item")
                        .WithMany("OrderDetails")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("order_details_item_id_fkey");

                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", "Order")
                        .WithMany("Details")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("order_details_order_id_fkey");

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", "User")
                        .WithMany("Orders")
                        .HasForeignKey("BorrowerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("orders_borrower_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("OrderDetails");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Navigation("Details");

                    b.Navigation("Media");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
