// <auto-generated />
using System;
using LendingSystem.SharedKernel.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LendingSystem.SharedKernel.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(LendingDbContext))]
    [Migration("20260523144256_UseSnowflakeIds")]
    partial class UseSnowflakeIds
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.BorrowerDetailEntity", b =>
                {
                    b.Property<long>("BorrowerDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("borrower_detail_id");

                    b.Property<string>("BorrowerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("borrower_name");

                    b.Property<DateOnly>("CreatedAt")
                        .HasColumnType("date")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("created_by");

                    b.Property<string>("Link")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("")
                        .HasColumnName("link");

                    b.Property<DateOnly>("UpdatedAt")
                        .HasColumnType("date")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasDefaultValue("")
                        .HasColumnName("updated_by");

                    b.Property<long?>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.HasKey("BorrowerDetailId")
                        .HasName("borrower_details_pkey");

                    b.HasIndex("UserId");

                    b.ToTable("borrower_details", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("CurrentStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("Available")
                        .HasColumnName("current_status");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("image_url");

                    b.Property<string>("Maker")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("maker");

                    b.Property<string>("Material")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("material");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("object_name");

                    b.Property<long>("OwnerId")
                        .HasColumnType("bigint")
                        .HasColumnName("owner_id");

                    b.HasKey("ItemId")
                        .HasName("items_pkey");

                    b.HasIndex("OwnerId");

                    b.ToTable("items", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemMediaEntity", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<long>("ItemId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("MediaId")
                        .HasName("item_media_pkey");

                    b.HasIndex("ItemId")
                        .HasDatabaseName("idx_item_media_item_id");

                    b.ToTable("item_media", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.LendingMediaEntity", b =>
                {
                    b.Property<long>("MediaId")
                        .HasColumnType("bigint")
                        .HasColumnName("media_id");

                    b.Property<DateTime?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Link")
                        .HasColumnType("text")
                        .HasColumnName("link");

                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("url");

                    b.HasKey("MediaId")
                        .HasName("lending_media_pkey");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("idx_lending_media_order_id");

                    b.ToTable("lending_media", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Property<long>("OrderId")
                        .HasColumnType("bigint")
                        .HasColumnName("order_id");

                    b.Property<DateOnly?>("ActualReturnDate")
                        .HasColumnType("date")
                        .HasColumnName("actual_return_date");

                    b.Property<long>("BorrowerDetailId")
                        .HasColumnType("bigint")
                        .HasColumnName("borrower_detail_id");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<long>("ObjectId")
                        .HasColumnType("bigint")
                        .HasColumnName("item_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("OrderId")
                        .HasName("orders_pkey");

                    b.HasIndex("BorrowerDetailId");

                    b.HasIndex("ObjectId");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", b =>
                {
                    b.Property<long>("UserId")
                        .HasColumnType("bigint")
                        .HasColumnName("user_id");

                    b.Property<string>("AuthProvider")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasDefaultValue("LOCAL")
                        .HasColumnName("auth_provider");

                    b.Property<DateTimeOffset?>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("email");

                    b.Property<bool>("IsDeleted")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false)
                        .HasColumnName("is_deleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PasswordHash")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("password_hash");

                    b.Property<string>("ProviderUserId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("provider_user_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text")
                        .HasDefaultValue("user")
                        .HasColumnName("role");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("UserId")
                        .HasName("users_pkey");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("users_email_key");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("users_name_key");

                    b.HasIndex("AuthProvider", "ProviderUserId")
                        .IsUnique()
                        .HasDatabaseName("users_auth_provider_provider_user_id_key");

                    b.ToTable("users", null, t =>
                        {
                            t.HasCheckConstraint("ck_users_name_english_letters", "name ~ '^[A-Za-z0-9]+$'");
                        });
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.BorrowerDetailEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .HasConstraintName("borrower_details_user_id_fkey");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.UserEntity", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemMediaEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", "Item")
                        .WithMany("Media")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_item_media_item");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.LendingMediaEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", "Order")
                        .WithMany("Media")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lending_media_order");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.BorrowerDetailEntity", "BorrowerDetail")
                        .WithMany("Orders")
                        .HasForeignKey("BorrowerDetailId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired()
                        .HasConstraintName("orders_borrower_detail_id_fkey");

                    b.HasOne("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", "Item")
                        .WithMany("Orders")
                        .HasForeignKey("ObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("orders_item_id_fkey");

                    b.Navigation("BorrowerDetail");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.BorrowerDetailEntity", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.ItemEntity", b =>
                {
                    b.Navigation("Media");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("LendingSystem.SharedKernel.Infrastructure.Persistence.OrderEntity", b =>
                {
                    b.Navigation("Media");
                });
#pragma warning restore 612, 618
        }
    }
}
